
name: Event Test

run-name: Fabric CICD Event - ${{ github.event_name }} - ${{ github.ref }}

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]


jobs:
  deployment-job:    
    name: Event Test
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install MSAL
        run: |
          pip install msal

      - name: Event Test
        run: 
          python src/handle_fabric_cicd_events.py